GET http://localhost:3000/movies


### recuperar una pelicula
GET http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

### recuperar peliculas por genero
GET http://localhost:3000/movies?genre=Sci-Fi


### crear una nueva pelicula
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title":"el miles morales 2",
    "year": 2023,
    "director":"no me acuerdo",
    "genre":["Action"],
    "ratio":10  
}


### actualizar una pelicula 
PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "year":"2005"
}

### borrara recurso
DELETE http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json